### ISSUE TITLE
定时命令系统插件导致备份插件出错？

### ISSUE THREAD

**Issue by imhanks** [yqs112358/LLPlugins#5]
![image](https://user-images.githubusercontent.com/85935640/158772595-ba9e1074-0760-4bd3-8243-0c2f21877a6d.png)
今天早上服务器日常备份时，LL报错，显示定时插件出错，接着一段时间后，“定时”按规定命令备份，却显示“An existing backup is working now .”
![image](https://user-images.githubusercontent.com/85935640/158773289-e39c38ed-2c11-4446-92c3-b44080858ddf.png)
我尝试了“backup reload” ，再“backup”，还是显示“An existing backup is working now .”
![image](https://user-images.githubusercontent.com/85935640/158773669-315d848f-025c-439d-9b0d-633a060b76a4.png)
在此问题出现前一切正常，直到今日
使用的插件： BackupHelper - 稳定、易用的BDS存档热备份插件 v 2.0.6
ScheduleCmd - 高自由度的的定时命令系统 v 1.1.1

**Comment by pa733** [comment]
对于这种情况，你需要先确认备份进程已完全停止，然后使用`save resume`来恢复

**Comment by yqs112358** [comment]
小问题，这个是偶尔出现的时序错误，其实重启下服就好了
